DROP TABLE IF EXISTS user_shifts CASCADE;

CREATE TABLE user_shifts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  shift_id INTEGER REFERENCES shifts(id) ON DELETE CASCADE,
  isPublished BOOLEAN DEFAULT FALSE
);